spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-micro-realm
  application:
    name: Api GateWay
server:
  port: 9000

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      name: Product Service
      url: /aggregate/product-service/v3/api-docs
    urls[1]:
      name: Order Service
      url: /aggregate/order-service/v3/api-docs
    urls[2]:
      name: Inventory Service
      url: /aggregate/inventory-service/v3/api-docs
  api-docs:
    path: /api-docs

#Actuator Endpoints
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: loan-service
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

# Resilience4j Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
#Resilience4j Timeout Properties
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 3
#Resilience4j Retry Properties
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration:
          seconds: 2