services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    ports:
      - "27019:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: user
      MONGODB_INITDB_ROOT_PASSWORD: password
      MONGODB_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db
